#!/bin/sh
cd /root/smartctl
/usr/bin/date > smartctl
/usr/sbin/smartctl --all /dev/sda >> smartctl
/usr/bin/git diff smartctl > diff
/usr/bin/git commit -a -m "$(/usr/bin/head -n 1 diff)"
/usr/bin/git push origin master
